### ISSUE TITLE
[tools.plot_utils] Regression in prealignment plotting

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#51]
Offset and error cuts are not plotted anymore:

![grafik](https://cloud.githubusercontent.com/assets/6951141/22704024/86c315fa-ed66-11e6-9966-79a5f742372a.png)

**Comment by laborleben** [comment]
The errorbars were removed because they filled up the complete screen several times. This made the plot completely useless.
Anyway, what kind of information do you expect to get in addition from the errorbars? They were also misleading in double Gaussian fit several times ( bad fit). So the offset was enough to select a good range. The precision is anyway good enough for the following alignment.

**Comment by laborleben** [comment]
They don't need to be plotted in this case because the fit range selects the data between the two red bars and the plot zooms in as much as possible with the maximum error/offset at the top of the plot.

**Comment by DavidLP** [comment]
> fit range selects the data between the two red bars

Which red bars? The blue red bars? ;-)

I actually had the impression that no matter what value I put for the error/offset cut, they never show up. I cross check.
